### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by escorciav** [escorciav/kaust-cluster-status#7]
Document what's going on under the hood

**Comment by ThunderLettuce** [comment]
What are you looking to have documented?

**Comment by escorciav** [comment]
Thanks for asking. These are the list of tasks for this issue.

- [ ] Improve README. Adding how to install environment, how to launch the sever, apply ngrok trick.

- [ ] Add few words about how the code works under the hood.

Lemme know if u wanna help out, and what u would need to do so.

**Comment by ThunderLettuce** [comment]
I'm interested and I just want to say I'm pretty new but I'm ready to learn
and help you out. What do I need to do?

**Comment by escorciav** [comment]
If you are at KAUST, you can start by cloning the repo and testing.

- [ ] Creating a conda environment with the dependencies listed [here](https://github.com/escorciav/kaust-cluster-status#usage), and test it in Ibex.

**Comment by escorciav** [comment]
Closed as it was accomplish with the last set of commits
